import '../data/models/job_listing_model.dart';

final List<JobListing> listings = [
  JobListing(
      id: 1,
      company: 'Spectrum',
      imageAsset: 'assets/data/pic-3.svg',
      workplace: 'Remote',
      level: 'Junior',
      location: 'Jakarta, Indonesia',
      monthlySalary: 7,
      title: 'UI Designer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 2,
      company: 'VK',
      imageAsset: 'assets/data/pic-2.svg',
      workplace: 'On Site',
      level: 'Senior',
      location: 'Jakarta, Indonesia',
      monthlySalary: 13,
      title: 'Software Engineer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 3,
      company: 'Discord',
      imageAsset: 'assets/data/pic-5.svg',
      workplace: 'Remote',
      level: 'Senior',
      location: 'California, United States',
      monthlySalary: 16,
      title: 'Backend Developer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 4,
      company: 'Invison',
      imageAsset: 'assets/data/pic-3.svg',
      workplace: 'Hybrid',
      level: 'Intern',
      location: 'Tokyo, Japan',
      monthlySalary: 11,
      title: 'Software Engineer',
      isSaved: false,
      type: 'Internship'),
  JobListing(
      id: 5,
      company: 'Behance',
      imageAsset: 'assets/data/pic-4.svg',
      workplace: 'Onsite',
      level: 'Associate',
      location: 'Jakarta, Indonesia',
      monthlySalary: 8,
      title: 'Frontend Developer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 6,
      company: 'Twitter',
      imageAsset: 'assets/data/pic-6.svg',
      workplace: 'Remote',
      level: 'Junior',
      location: 'New York, United States',
      monthlySalary: 7,
      title: 'UI/UX Designer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 7,
      company: 'Facebook',
      imageAsset: 'assets/data/pic-7.svg',
      workplace: 'Remote',
      level: 'Junior',
      location: 'Jakarta, Indonesia',
      monthlySalary: 12,
      title: 'UI Designer',
      isSaved: false,
      type: 'Fulltime'),
  JobListing(
      id: 8,
      company: 'Instagram',
      imageAsset: 'assets/data/pic-8.svg',
      workplace: 'Onsite',
      level: 'Senior',
      location: 'Jakarta, Indonesia',
      monthlySalary: 16,
      title: 'Database Adminstrator',
      isSaved: false,
      type: 'Fulltime'),
];
